#! /bin/sh
# Script ejemplo para arranque de servicios en /etc/init.d/
#

case "$1" in
start)
	echo "Iniciando servicio... "
	python /home/j.alvarez//Computacion_en_Red/Lector_de_cotizaciones/Lector_Bolsa.py 1>/dev/null &
	python /home/j.alvarez/Computacion_en_Red/Aplicacion_bolsa.py &
	;;
stop)
	echo "Deteniendo servicio..."
	# Aquí comando a ejecutar para detener el servicio
	ps -ef | grep -i Lector_Bolsa | grep -v grep | awk '{ print $2 }' | xargs sudo kill -9
	ps -ef | grep -i Aplicacion_bolsa | grep -v grep | awk '{ print $2 }' | xargs sudo kill -9
	;;
restart)
	echo "Deteniendo servicio..."
        # Aquí comando a ejecutar para detener el servicio
        ps -ef | grep -i Lector_Bolsa | grep -v grep | awk '{ print $2 }' | xargs sudo kill -9
        ps -ef | grep -i Aplicacion_bolsa | grep -v grep | awk '{ print $2 }' | xargs sudo kill -9
        echo "Iniciando servicio... "
        python /home/j.alvarez/Computacion_en_Red/Lector_de_cotizaciones/Lector_Bolsa.py 1>/dev/null &
        python /home/j.alvarez/Computacion_en_Red/Aplicacion_bolsa.py  &
        ;;
*)
	echo "Modo de empleo: /etc/init.d/Lector_datos {start|stop|restart}"
	exit 1
	;;
esac
exit 0


